repos:
  # ------------------------
  # Linting
  # ------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.0
    hooks:
      # Run the linter.
      - id: ruff-check

  # ------------------------
  # Formatting
  # ------------------------
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # ------------------------
  # Local hooks
  # ------------------------
  - repo: local
    hooks:
        - id: pytest-unit
          name: pytest unit tests
          entry: pytest tests/unit -q -x
          language: system
          pass_filenames: false
          stages: [ pre-commit ]