name: semantic_search
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - jupyterlab
  - pip
  - pip:
      - pytest
      - matplotlib
      - pandas
      - langchain-openai
      - langchain-chroma
      - langchain-core
      - langchain-text-splitters
      - langchain-ollama